#:kivy 2.3.0

<RootLayout@BoxLayout>:
    orientation: "vertical"
    padding: dp(8)
    spacing: dp(6)

    ScrollView:
        id: scroll
        do_scroll_x: False

        BoxLayout:
            id: chat_box
            orientation: "vertical"
            size_hint_y: None
            height: self.minimum_height
            spacing: dp(8)

    BoxLayout:
        size_hint_y: None
        height: dp(56)
        spacing: dp(6)

        TextInput:
            id: input
            hint_text: "Написать…"
            multiline: False

        Button:
            text: "➤"
            size_hint_x: None
            width: dp(48)
            on_release: app.on_send()
